__version__ = "0.0.0"
__author__ = "Hrishikesh Belagali" 
__author_email__ = "belagal1@msu.edu"
__url__ = "https://github.com/lonelyneutrin0/ovito-stride"
__description__ = "A plugin for OVITO to compute the Stride of a system."